version: '3'
services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    restart: always
    ports:
      - "2222:2222"
    volumes:
      - ./honeypot/cowrie/etc/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./honeypot/cowrie/var:/cowrie/cowrie-git/var
